# Polynomial Regression

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data = pd.read_csv("insurance.csv")

In [ ]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female     NaN         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1327 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
data.isna().sum()

age          0
sex          0
bmi         11
children     0
smoker       0
region       0
charges      0
dtype: int64

In [ ]:
data.bmi.fillna(data.bmi.mean(),inplace=True)

/tmp/ipykernel_9754/3394024120.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.bmi.fillna(data.bmi.mean(),inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(1)

In [ ]:
data.drop_duplicates(inplace=True); data.reset_index(drop=True, inplace=True)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
encoded_categories = ohe.fit_transform(data.select_dtypes('O'))

In [ ]:
encoded_categories = encoded_categories.toarray()

In [ ]:
encoded_categories = pd.DataFrame(data=encoded_categories, columns=ohe.get_feature_names_out())

In [ ]:
numbered_data = data.select_dtypes('number')
numbered_data

      age        bmi  children      charges
0      19  30.667841         0  16884.92400
1      18  33.770000         1   1725.55230
2      28  33.000000         3   4449.46200
3      33  22.705000         0  21984.47061
4      32  28.880000         0   3866.85520
...   ...        ...       ...          ...
1332   50  30.970000         3  10600.54830
1333   18  31.920000         0   2205.98080
1334   18  36.850000         0   1629.83350
1335   21  25.800000         0   2007.94500
1336   61  29.070000         0  29141.36030

[1337 rows x 4 columns]

In [ ]:
df = pd.concat([numbered_data,encoded_categories],axis=1)

In [ ]:
df

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,region_northwest,region_southeast,region_southwest
0,19,30.667841,0,16884.92400,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,18,33.770000,1,1725.55230,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,28,33.000000,3,4449.46200,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,33,22.705000,0,21984.47061,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,32,28.880000,0,3866.85520,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,50,30.970000,3,10600.54830,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1333,18,31.920000,0,2205.98080,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1334,18,36.850000,0,1629.83350,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1335,21,25.800000,0,2007.94500,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1336,61,29.070000,0,29141.36030,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
df.dropna(inplace=True, axis=0)
df

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,region_northwest,region_southeast,region_southwest
0,19,30.667841,0,16884.92400,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,18,33.770000,1,1725.55230,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,28,33.000000,3,4449.46200,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,33,22.705000,0,21984.47061,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,32,28.880000,0,3866.85520,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,50,30.970000,3,10600.54830,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1333,18,31.920000,0,2205.98080,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1334,18,36.850000,0,1629.83350,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1335,21,25.800000,0,2007.94500,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1336,61,29.070000,0,29141.36030,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
X = df.drop('charges', axis=1)
y = df.charges

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)

In [ ]:
X = pd.DataFrame(data=X_poly, columns=poly.get_feature_names_out())
X

,1,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,...,region_northeast^2,region_northeast region_northwest,region_northeast region_southeast,region_northeast region_southwest,region_northwest^2,region_northwest region_southeast,region_northwest region_southwest,region_southeast^2,region_southeast region_southwest,region_southwest^2
0,1.0,19.0,30.667841,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,18.0,33.770000,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,28.0,33.000000,3.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.0,33.0,22.705000,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,32.0,28.880000,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,1.0,50.0,30.970000,3.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1333,1.0,18.0,31.920000,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1334,1.0,18.0,36.850000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1335,1.0,21.0,25.800000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1336,1.0,61.0,29.070000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
from sklearn.metrics import r2_score

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred_train = lr.predict(X_train)

In [ ]:
r2_score(y_train, y_pred_train)

0.826556754718664