In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [ ]:
data = pd.read_csv('Student_Performance.csv')

In [ ]:
data.shape

(10000, 6)

In [ ]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  int64
dtypes: int64(5), object(1)
memory usage: 468.9+ KB

In [ ]:
data.duplicated().sum()

np.int64(127)

In [ ]:
data["Extracurricular Activities"].replace({"Yes":1,"No":0},inplace=True)

/tmp/ipykernel_7228/1627601247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Extracurricular Activities"].replace({"Yes":1,"No":0},inplace=True)
/tmp/ipykernel_7228/1627601247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Extracurricular Activities"].replace({"Yes":1,"No":0},inplace=True)

In [ ]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66

In [ ]:
X=data.drop("Performance Index",axis=1)
y=data["Performance Index"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn import linear_model
lr = linear_model.LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred_train = lr.predict(X_train)

In [ ]:
from sklearn.metrics import r2_score , mean_squared_error
mean_squared_error(y_train,y_pred_train)

4.169735849525007

In [ ]:
r2_score(y_train,y_pred_train)

0.9886898790682355

In [ ]:
y_pred_test = lr.predict(X_test)

In [ ]:
mean_squared_error(y_test,y_pred_test)

4.082628398521853

In [ ]:
r2_score(y_test,y_pred_test)

0.9889832909573145