In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("Loan_approval_data_2025.csv")

In [ ]:
data

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST149995,35,Employed,4.3,39449,570,16.3,1127,7576,0,0,0,Credit Card,Education,42800,21.31,0.192,1.085,0.362,0
49996,CUST149996,34,Employed,4.4,20496,672,12.6,1478,6276,1,0,0,Credit Card,Personal,3800,18.07,0.306,0.185,0.062,0
49997,CUST149997,41,Self-Employed,4.8,18743,719,10.1,17,10331,0,0,0,Credit Card,Personal,18000,17.45,0.551,0.960,0.320,0
49998,CUST149998,38,Student,0.4,17250,633,1.3,5,7779,0,0,1,Personal Loan,Personal,1400,14.71,0.451,0.081,0.027,0
49999,CUST149999,53,Employed,17.2,46923,695,15.0,8332,2655,0,1,0,Personal Loan,Personal,41000,12.39,0.057,0.874,0.291,1

In [ ]:
data.shape

(50000, 20)

In [ ]:
data = data.drop(['customer_id','defaults_on_file'],axis=1)

In [ ]:
data.occupation_status.unique()

array(['Employed', 'Student', 'Self-Employed'], dtype=object)

In [ ]:
data.product_type.unique()

array(['Credit Card', 'Personal Loan', 'Line of Credit'], dtype=object)

In [ ]:
data.loan_intent.unique()

array(['Business', 'Home Improvement', 'Debt Consolidation', 'Education',
       'Personal', 'Medical'], dtype=object)

In [ ]:
cat_cols = data.select_dtypes(include='object').columns
cat_cols

Index(['occupation_status', 'product_type', 'loan_intent'], dtype='object')

## performing One Hit Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
encoded_cat_data = ohe.fit_transform(data[cat_cols]).toarray()
cat_data = pd.DataFrame(encoded_cat_data,columns=ohe.get_feature_names_out())
cat_data

,occupation_status_Employed,occupation_status_Self-Employed,occupation_status_Student,product_type_Credit Card,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Business,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
49996,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49997,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49998,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
49999,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
encoded_data = pd.concat([data,cat_data],axis=1).drop(cat_cols,axis=1)
encoded_data.head()
# pd.concat([data.drop(cat_cols,axis=1),cat_data],axis=1)

,age,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,delinquencies_last_2yrs,derogatory_marks,loan_amount,...,occupation_status_Student,product_type_Credit Card,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Business,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal
0,40,17.2,25579,692,5.3,895,10820,0,0,600,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,33,7.3,43087,627,3.5,169,16550,1,0,53300,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,42,1.1,20840,689,8.4,17,7852,0,0,2100,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,53,0.5,29147,692,9.8,1480,11603,1,0,2900,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,32,12.5,63657,630,7.2,209,12424,0,0,99600,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_ohe = encoded_data.drop('loan_status', axis=1)
y_ohe = encoded_data['loan_status']

X_train_ohe, X_test_ohe, y_train_ohe, y_test_ohe = train_test_split(X_ohe, y_ohe, test_size=0.2, random_state=42)

log_reg_model_ohe = LogisticRegression(random_state=42, max_iter=1000)
log_reg_model_ohe.fit(X_train_ohe, y_train_ohe)

y_pred_ohe = log_reg_model_ohe.predict(X_test_ohe)

print("Classification Report for OHE data:")
print(classification_report(y_test_ohe, y_pred_ohe))

Classification Report for OHE data:
              precision    recall  f1-score   support

           0       0.80      0.76      0.78      4509
           1       0.81      0.84      0.83      5491

    accuracy                           0.81     10000
   macro avg       0.81      0.80      0.80     10000
weighted avg       0.81      0.81      0.81     10000

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## performing Standard Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

X = encoded_data.drop('loan_status', axis=1)
y = encoded_data['loan_status']

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

scaled_data = pd.concat([X_scaled_df, y], axis=1)

In [ ]:
display(scaled_data)

,age,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,delinquencies_last_2yrs,derogatory_marks,loan_amount,...,product_type_Credit Card,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Business,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal,loan_status
0,0.453563,1.280229,-0.750345,0.747482,-0.397958,-0.204093,-0.262046,-0.656347,-0.357489,-1.242226,...,1.107554,-0.500687,-0.734541,2.386281,-0.330251,-0.504184,-0.418534,-0.423308,-0.575164,1
1,-0.176018,-0.020345,-0.213787,-0.256675,-0.647698,-0.258959,0.170615,0.527028,-0.357489,0.775700,...,-0.902891,-0.500687,1.361394,-0.419062,-0.330251,-0.504184,2.389290,-0.423308,-0.575164,0
2,0.633444,-0.834846,-0.895579,0.701137,0.032151,-0.270446,-0.486154,-0.656347,-0.357489,-1.184790,...,1.107554,-0.500687,-0.734541,-0.419062,3.028003,-0.504184,-0.418534,-0.423308,-0.575164,1
3,1.622787,-0.913669,-0.640998,0.747482,0.226393,-0.159883,-0.202923,0.527028,-0.357489,-1.154157,...,1.107554,-0.500687,-0.734541,2.386281,-0.330251,-0.504184,-0.418534,-0.423308,-0.575164,1
4,-0.265959,0.662785,0.416612,-0.210330,-0.134343,-0.255936,-0.140931,-0.656347,-0.357489,2.548565,...,-0.902891,-0.500687,1.361394,-0.419062,-0.330251,1.983403,-0.418534,-0.423308,-0.575164,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.003862,-0.414459,-0.325278,-1.137244,1.128234,-0.186561,-0.506994,-0.656347,-0.357489,0.373647,...,1.107554,-0.500687,-0.734541,-0.419062,-0.330251,1.983403,-0.418534,-0.423308,-0.575164,0
49996,-0.086078,-0.401322,-0.906121,0.438511,0.614879,-0.160035,-0.605155,-0.656347,-0.357489,-1.119695,...,1.107554,-0.500687,-0.734541,-0.419062,-0.330251,-0.504184,-0.418534,-0.423308,1.738634,0
49997,0.543504,-0.348773,-0.959844,1.164594,0.268017,-0.270446,-0.298970,-0.656347,-0.357489,-0.575966,...,1.107554,-0.500687,-0.734541,-0.419062,-0.330251,-0.504184,-0.418534,-0.423308,1.738634,0
49998,0.273683,-0.926806,-1.005600,-0.163984,-0.952937,-0.271353,-0.491666,-0.656347,2.063865,-1.211593,...,-0.902891,-0.500687,1.361394,-0.419062,-0.330251,-0.504184,-0.418534,-0.423308,1.738634,0
49999,1.622787,1.280229,-0.096227,0.793828,0.947866,0.357942,-0.878569,0.527028,-0.357489,0.304723,...,-0.902891,-0.500687,1.361394,-0.419062,-0.330251,-0.504184,-0.418534,-0.423308,1.738634,1

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X = scaled_data.drop('loan_status', axis=1)
y = scaled_data['loan_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
log_reg_model = LogisticRegression(random_state=42)
log_reg_model.fit(X_train, y_train)

y_pred = log_reg_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      4509
           1       0.87      0.87      0.87      5491

    accuracy                           0.86     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.86      0.86      0.86     10000